data_path: "../data/raw/speech_commands_v0.01/"
test_file: "testing_list.txt"
val_file: "validation_list.txt"
train_data_path: "../data/processed/train.csv"
val_data_path: "../data/processed/val.csv"
test_data_path: "../data/processed/test.csv"
# model_path: "models/oratio_model.h5"
model_path: "projects/426550053563/locations/us-central1/endpoints/8057260790761127936"